apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-v2
  labels:
    app: message-service
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-service
      version: v2
  template:
    metadata:
      labels:
        app: message-service
        version: v2
    spec:
      containers:
      - name: message-service
        image: evntual/message-service:v2.0.0
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
          - containerPort: 5000
        env:
          - name: MONGO_SERVICE
            value: servicio-mongodb
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: password
          - name: USER_SERVICE
            value: user-service
          - name: USER_SERVICE_PORT
            value: "5001"