apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-v2
  labels:
    app: auth-service
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      version: v2
  template:
    metadata:
      labels:
        app: auth-service
        version: v2
    spec:
      containers:
      - name: auth-service
        image: evntual/auth-service:v2.0.0
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
          - containerPort: 5002
        env:
          - name: REDIS_SERVICE
            value: servicio-redis
          - name: REDIS_SERVICE_PORT
            value: "6379"
          - name: USER_SERVICE
            value: user-service
          - name: USER_SERVICE_PORT
            value: "5001"