apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-v2
  labels:
    app: gateway-service
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
      version: v2
  template:
    metadata:
      labels:
        app: gateway-service
        version: v2
    spec:
      containers:
      - name: gateway-service
        image: evntual/gateway-service:v2.0.0
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
          - containerPort: 5003
        env:
          - name: USER_SERVICE
            value: user-service
          - name: USER_SERVICE_PORT
            value: "5001"
          - name: MESSAGE_SERVICE
            value: message-service
          - name: MESSAGE_SERVICE_PORT
            value: "5000"
          - name: AUTH_SERVICE
            value: auth-service
          - name: AUTH_SERVICE_PORT
            value: "5002"