version: "3.9"
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-volumen:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
  user-service:
    image: evntual/user-service:v2.0.0
    environment:
      - MONGO_SERVICE=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
    #ports:
    # - 5001:5001
  message-service:
    image: evntual/message-service:v2.0.0
    environment:
      - MONGO_SERVICE=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - USER_SERVICE=user-service
      - USER_SERVICE_PORT=5001
    #ports:
    # - 5000:5000
  auth-service:
    image: evntual/auth-service:v2.0.0
    environment:
      - REDIS_SERVICE=redis
      - REDIS_SERVICE_PORT=6379
      - USER_SERVICE=user-service
      - USER_SERVICE_PORT=5001
    #ports:
    #  - 5002:5002
  gateway-service:
    image: evntual/gateway-service:v2.0.0
    environment:
      - USER_SERVICE=user-service
      - USER_SERVICE_PORT=5001
      - MESSAGE_SERVICE=message-service
      - MESSAGE_SERVICE_PORT=5000
      - AUTH_SERVICE=auth-service
      - AUTH_SERVICE_PORT=5002
    ports:
      - 5003:5003

volumes:
  mongo-volumen: #nuevo volumen gestionado por docker, se crea si no existe, se reúsa si ya existe      